In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [22]:
df_fbs = pd.read_csv('Live.csv')

In [26]:
df_fbs['status_id'].nunique()

6997

In [29]:
df_fbs['status_type']

status_type
photo     4288
video     2334
status     365
link        63
Name: count, dtype: int64

In [33]:
df_fbs['status_published'] = pd.to_datetime(df_fbs['status_published'])

In [41]:
df_fbs[df_fbs['status_published']=='4/19/2018 22:26'][['status_type','num_likes']]

     status_type  num_likes
4592       photo        379

In [44]:
df_fbs[df_fbs['status_published'] == '7/15/2017 10:52'][['num_shares','status_type']]

      num_shares status_type
6977         167       video

In [ ]:
colour=['red','blue','green','yellow','cyan']
n=0
for i in range(0,len(colour)):
  plt.scatter(X[df['Clusters(5)']==i],Y[df['Clusters(5)']==i],s=10,c=colour[i])
  plt.scatter(k.cluster_centers_[:,0],k.cluster_centers_[:,1], color='black')

In [45]:
df_fbs3 = df_fbs.copy()

In [46]:
df_fbs3 = df_fbs3.drop(columns=['status_id', 'status_published'])

In [64]:
X = df_fbs3.iloc[:,:-4]

In [53]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import LabelEncoder

min_max_scaler = MinMaxScaler()
le = LabelEncoder()

In [54]:
X['status_type'] = le.fit_transform(X['status_type'])

In [57]:
X = X.iloc[:, :-4]

In [58]:
min_max_scaler.fit_transform(X)

array([[1.00000000e+00, 1.12314225e-01, 2.43925679e-02, ...,
        6.36942675e-03, 1.96078431e-02, 0.00000000e+00],
       [3.33333333e-01, 3.18471338e-02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 4.81953291e-02, 1.12434493e-02, ...,
        6.36942675e-03, 0.00000000e+00, 0.00000000e+00],
       ...,
       [3.33333333e-01, 4.24628450e-04, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.33333333e-01, 7.45222930e-02, 5.71700810e-04, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.33333333e-01, 3.60934183e-03, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [60]:
from sklearn.cluster import KMeans
kmodel = KMeans(n_clusters=2, random_state=42)

In [61]:
kmodel.fit(X)

KMeans(n_clusters=2, random_state=42)

In [63]:
kmodel.inertia_

4986397875.914615

In [6]:
# Exploratory Data Analysis
df_fbs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7050 entries, 0 to 7049
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   status_id         7050 non-null   object
 1   status_type       7050 non-null   object
 2   status_published  7050 non-null   object
 3   num_reactions     7050 non-null   int64
 4   num_comments      7050 non-null   int64
 5   num_shares        7050 non-null   int64
 6   num_likes         7050 non-null   int64
 7   num_loves         7050 non-null   int64
 8   num_wows          7050 non-null   int64
 9   num_hahas         7050 non-null   int64
 10  num_sads          7050 non-null   int64
 11  num_angrys        7050 non-null   int64
 12  Column1           0 non-null      float64
 13  Column2           0 non-null      float64
 14  Column3           0 non-null      float64
 15  Column4           0 non-null      float64
dtypes: float64(4), int64(9), object(3)
memory usage: 881.4+ KB

In [7]:
df_fbs.sample(10)

,status_id,status_type,status_published,num_reactions,num_comments,num_shares,num_likes,num_loves,num_wows,num_hahas,num_sads,num_angrys,Column1,Column2,Column3,Column4
306,246675545449582_1250548631728930,photo,4/8/2017 9:51,77,13,4,77,0,0,0,0,0,NaN,NaN,NaN,NaN
6053,614855718638584_656449171145905,photo,11/22/2017 2:24,16,1,1,16,0,0,0,0,0,NaN,NaN,NaN,NaN
4826,614855718638584_849318975192256,photo,6/8/2018 2:10,40,1,0,40,0,0,0,0,0,NaN,NaN,NaN,NaN
3985,117059915488335_368786656982325,video,6/10/2018 21:03,186,817,68,154,27,2,3,0,0,NaN,NaN,NaN,NaN
1434,246675545449582_518231948293939,video,3/11/2014 5:12,722,9,1,722,0,0,0,0,0,NaN,NaN,NaN,NaN
5554,614855718638584_704238806366941,photo,1/15/2018 7:58,102,8,3,100,2,0,0,0,0,NaN,NaN,NaN,NaN
5072,614855718638584_835043073286513,photo,5/25/2018 1:51,8,0,0,8,0,0,0,0,0,NaN,NaN,NaN,NaN
2692,134115277150304_264416247453539,photo,5/31/2018 3:12,72,13,1,69,3,0,0,0,0,NaN,NaN,NaN,NaN
6064,614855718638584_655718721218950,photo,11/21/2017 2:37,20,0,0,20,0,0,0,0,0,NaN,NaN,NaN,NaN
5475,614855718638584_722262794564542,video,2/3/2018 7:05,128,571,110,92,35,0,0,0,1,NaN,NaN,NaN,NaN

In [8]:
df_fbs['status_type'].value_counts()

status_type
photo     4288
video     2334
status     365
link        63
Name: count, dtype: int64

In [9]:
df_fbs.describe()

,num_reactions,num_comments,num_shares,num_likes,num_loves,num_wows,num_hahas,num_sads,num_angrys,Column1,Column2,Column3,Column4
count,7050.000000,7050.000000,7050.000000,7050.000000,7050.000000,7050.000000,7050.000000,7050.000000,7050.000000,0.0,0.0,0.0,0.0
mean,230.117163,224.356028,40.022553,215.043121,12.728652,1.289362,0.696454,0.243688,0.113191,NaN,NaN,NaN,NaN
std,462.625309,889.636820,131.599965,449.472357,39.972930,8.719650,3.957183,1.597156,0.726812,NaN,NaN,NaN,NaN
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
25%,17.000000,0.000000,0.000000,17.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
50%,59.500000,4.000000,0.000000,58.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
75%,219.000000,23.000000,4.000000,184.750000,3.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
max,4710.000000,20990.000000,3424.000000,4710.000000,657.000000,278.000000,157.000000,51.000000,31.000000,NaN,NaN,NaN,NaN

In [15]:
df_fbs.iloc[:,:-4].isnull().sum().sum()
df_fbs2 = df_fbs.iloc[:,:-4]

In [16]:
df_fbs2.isnull().sum().sum()

np.int64(0)

In [19]:
df_fbs2.shape

(7050, 12)

In [20]:
df_fbs2.duplicated().sum()
df_fbs2 = df_fbs2.drop_duplicates()

In [21]:
df_fbs2.shape

(6999, 12)

In [65]:
df_fbs2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6999 entries, 0 to 7049
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   status_id         6999 non-null   object
 1   status_type       6999 non-null   object
 2   status_published  6999 non-null   object
 3   num_reactions     6999 non-null   int64
 4   num_comments      6999 non-null   int64
 5   num_shares        6999 non-null   int64
 6   num_likes         6999 non-null   int64
 7   num_loves         6999 non-null   int64
 8   num_wows          6999 non-null   int64
 9   num_hahas         6999 non-null   int64
 10  num_sads          6999 non-null   int64
 11  num_angrys        6999 non-null   int64
dtypes: int64(9), object(3)
memory usage: 710.8+ KB

In [67]:
df_fbs2 = df_fbs2.drop(columns=['status_id', 'status_published'])

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [68]:
df_fbs2['status_type'] = LabelEncoder().fit_transform(df_fbs2['status_type'])

In [69]:
df_fbs2 = MinMaxScaler().fit_transform(df_fbs2)

In [70]:
kmodel2 = KMeans(n_clusters=2, random_state=24)

In [71]:
kmodel2.fit(df_fbs2)

KMeans(n_clusters=2, random_state=24)

In [72]:
kmodel2.inertia_

231.07549449079224