In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pandas.plotting import scatter_matrix

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier # DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor # RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB

from sklearn.svm import SVC

from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder

from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [ ]:
df_gym = pd.read_csv('GYM.csv')

In [ ]:
df_gym.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62184 entries, 0 to 62183
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   number_people         62184 non-null  int64
 1   day_of_week           62184 non-null  int64
 2   is_weekend            62184 non-null  int64
 3   is_holiday            62184 non-null  int64
 4   temperature           62184 non-null  float64
 5   is_start_of_semester  62184 non-null  int64
 6   is_during_semester    62184 non-null  int64
 7   month                 62184 non-null  int64
 8   hour                  62184 non-null  int64
dtypes: float64(1), int64(8)
memory usage: 4.3 MB

In [ ]:
df_gym.describe()

,number_people,day_of_week,is_weekend,is_holiday,temperature,is_start_of_semester,is_during_semester,month,hour
count,62184.000000,62184.000000,62184.000000,62184.000000,62184.000000,62184.000000,62184.000000,62184.000000,62184.000000
mean,29.072543,2.982504,0.282870,0.002573,58.557108,0.078831,0.660218,7.439824,12.236460
std,22.689026,1.996825,0.450398,0.050660,6.316396,0.269476,0.473639,3.445069,6.717631
min,0.000000,0.000000,0.000000,0.000000,38.140000,0.000000,0.000000,1.000000,0.000000
25%,9.000000,1.000000,0.000000,0.000000,55.000000,0.000000,0.000000,5.000000,7.000000
50%,28.000000,3.000000,0.000000,0.000000,58.340000,0.000000,1.000000,8.000000,12.000000
75%,43.000000,5.000000,1.000000,0.000000,62.280000,0.000000,1.000000,10.000000,18.000000
max,145.000000,6.000000,1.000000,1.000000,87.170000,1.000000,1.000000,12.000000,23.000000

In [ ]:
df_gym.isnull().sum().sum()

np.int64(0)

In [ ]:
df_gym.duplicated().sum()
# df_gym.fillna()

np.int64(14218)

In [ ]:
# df_gym = pd.read_csv('GYM.csv')
# df_gym = df_gym.drop_duplicates()

In [ ]:
df_gym.corr().min().min()

-0.1739578122762517

In [ ]:
ss_gym = StandardScaler().fit_transform(df_gym.iloc[:,:-1])

In [ ]:
cov_gym = np.cov(ss_gym.T)
cov_gym

array([[ 1.00001608, -0.16206447, -0.17396061, -0.04825012,  0.3733333 ,
         0.18268584,  0.33535575, -0.09785512],
       [-0.16206447,  1.00001608,  0.79135092, -0.07586326,  0.01116891,
        -0.01178221, -0.00482371,  0.01555894],
       [-0.17396061,  0.79135092,  1.00001608, -0.03189935,  0.02067367,
        -0.01664604, -0.03612777,  0.00846248],
       [-0.04825012, -0.07586326, -0.03189935,  1.00001608, -0.08852802,
        -0.01485815, -0.07079957, -0.09494382],
       [ 0.3733333 ,  0.01116891,  0.02067367, -0.08852802,  1.00001608,
         0.09324336,  0.15247835,  0.0631256 ],
       [ 0.18268584, -0.01178221, -0.01664604, -0.01485815,  0.09324336,
         1.00001608,  0.20986547, -0.13716182],
       [ 0.33535575, -0.00482371, -0.03612777, -0.07079957,  0.15247835,
         0.20986547,  1.00001608,  0.09655723],
       [-0.09785512,  0.01555894,  0.00846248, -0.09494382,  0.0631256 ,
        -0.13716182,  0.09655723,  1.00001608]])

In [ ]:
eig_val, eig_vec = np.linalg.eig(cov_gym)

In [ ]:
eig_val

array([1.92509186, 1.62554618, 0.20668608, 0.49834257, 1.16810664,
       0.73610627, 0.92875016, 0.91149889])

In [ ]:
eig_vec

array([[ 0.42836462, -0.40824033, -0.00812315,  0.70747285, -0.07550699,
         0.26286826,  0.24299714, -0.12414155],
       [-0.57600678, -0.38642945,  0.70609599,  0.09257614, -0.07200581,
         0.06822634,  0.03640842,  0.02411093],
       [-0.58256141, -0.36815779, -0.70622326,  0.08619098, -0.09567119,
         0.02882877,  0.08904706,  0.03143901],
       [ 0.00754922,  0.22278235,  0.03866551,  0.00650953, -0.43667891,
        -0.0880072 ,  0.61464763,  0.61036726],
       [ 0.20944902, -0.45165624,  0.02130962, -0.45726005,  0.16483411,
        -0.38945344,  0.523461  , -0.29956838],
       [ 0.18786388, -0.31623647,  0.00238398,  0.09025713, -0.43827393,
        -0.62555036, -0.48445905,  0.19609121],
       [ 0.25256701, -0.44046944, -0.02560538, -0.42107709,  0.08892028,
         0.49947496, -0.21121843,  0.5120935 ],
       [-0.04830456, -0.02877139, -0.00085633,  0.29816361,  0.74974081,
        -0.35384546,  0.02409379,  0.4690823 ]])

In [ ]:
# cumulative sum of explained variance ratio in percentage
tot_var = eig_val.sum()
explained_var_ratio = [v / tot_var * 100 for v in sorted(eig_val, reverse=True)]
explained_var_ratio

[np.float64(24.06326121417865),
 np.float64(20.3190005468922),
 np.float64(14.601098239596766),
 np.float64(11.609190337725895),
 np.float64(11.39355290235679),
 np.float64(9.201180426232662),
 np.float64(6.229181942080781),
 np.float64(2.5835343909362662)]

In [ ]:
tot_var

np.float64(8.000128652525607)

In [ ]:
np.cumsum(explained_var_ratio)

array([ 24.06326121,  44.38226176,  58.98336   ,  70.59255034,
        81.98610324,  91.18728367,  97.41646561, 100.        ])

In [ ]:
pca_model = PCA(n_components=2)
pca_gym = pca_model.fit_transform(ss_gym)

In [ ]:
tot_var - pca_model.explained_variance_.sum()

np.float64(4.44949061273926)

In [ ]:
inverse_data = pca_model.inverse_transform(pca_gym)

In [ ]:
inverse_data

array([[ 2.52517258e-01, -1.03131283e-03, -9.24713774e-03, ...,
         1.60397271e-01,  2.21183613e-01, -1.40202498e-03],
       [ 3.75981080e-01, -3.24070298e-02, -4.42429603e-02, ...,
         2.34292522e-01,  3.22734196e-01, -4.55646478e-03],
       [ 2.98816191e-01, -1.27972067e-02, -2.23705712e-02, ...,
         1.88107990e-01,  2.59265082e-01, -2.58493991e-03],
       ...,
       [-2.29655566e-01,  1.21517250e+00,  1.20703461e+00, ...,
         3.22248579e-02,  5.81649119e-02,  9.83834393e-02],
       [-3.37686410e-01,  1.24262625e+00,  1.23765596e+00, ...,
        -3.24334863e-02, -3.06918484e-02,  1.01143574e-01],
       [-2.60521521e-01,  1.22301643e+00,  1.21578357e+00, ...,
         1.37510452e-02,  3.27772661e-02,  9.91720492e-02]])

In [ ]:
ss_gym.var(axis=0).sum() - inverse_data.var(axis=0).sum()

np.float64(4.449419059114334)

In [ ]:
?np.var

In [ ]:
# X = df_gym.iloc[:, :-1]
X_scaled = ss_gym
y = df_gym.iloc[:, -1]

In [ ]:
# X.shape

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [ ]:
# x_train.shape
# x_test.shape
# y_test.shape

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(x_train, y_train)

LinearRegression()

In [ ]:
y_test

44802     3
51279    17
36816    22
2503     23
53035     2
         ..
41289     1
17170    19
51989    17
43332    10
30459     1
Name: hour, Length: 12437, dtype: int64

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
y_pred

array([ 5.63899623, 12.63729046, 14.43639992, ..., 12.57141912,
       14.83588664,  8.16001918])

In [ ]:
nopca_rmse = np.sqrt(mean_squared_error(y_test, y_pred))

In [ ]:
pca_model = PCA(n_components=4)

In [ ]:
pca_data = pca_model.fit_transform(ss_gym)

In [ ]:
x_train2, x_test2, y_train2, y_test2 = train_test_split(pca_data, y, test_size=0.20, random_state=24)

In [ ]:
model2 = LinearRegression()

In [ ]:
model2.fit(x_train2, y_train2)

LinearRegression()

In [ ]:
y_pred_pca = model2.predict(x_test2)

In [ ]:
mean_squared_error(y_test2, y_pred_pca)

38.061617011067526

In [ ]:
pca_model.explained_variance_ratio_

array([0.24063261, 0.20319001, 0.14601098, 0.1160919 ])